# Generated by Django 5.2.17 on 2026-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_shell_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
